### ISSUE TITLE
does not work for me, please help

### ISSUE THREAD

**Issue by xhums1** [Watfaq/SoftU2F-Win#10]
Hi and let me tell you thank you for your work.
I have a problem, I managed to install the driver, all is ok (nu driver status error), windows is in test mode, I use chrome browser. I'm stuck at get your key in the computer, there is no message like in your printscreen for me, nothing shows up. What can be the problem?
![2](https://user-images.githubusercontent.com/9310833/156481218-2f3d4561-996d-49b9-9e16-4b150f34a5de.png)
![3](https://user-images.githubusercontent.com/9310833/156481225-29a74636-3176-452b-b81d-f96c00e66505.png)
![1](https://user-images.githubusercontent.com/9310833/156481226-54ff962f-3711-4636-bcdc-d4640377e00a.png)
?

**Comment by ibigbug** [comment]
have you also run the daemon on your machine?

**Comment by xhums1** [comment]
> have you also run the daemon on your machine?

NO :) now it works but I have another problem. I will open a new issue
Thanks!
