### ISSUE TITLE
Device not started

### ISSUE THREAD

**Issue by spiri439** [Watfaq/SoftU2F-Win#12]
Hello, 

I installed the driver and the certificate but it still says Device not started. I attached 2 screenshosts.

Thanks

![Screenshot 2022-03-09 145155](https://user-images.githubusercontent.com/14981875/157445279-8bd59d30-48e9-4b2a-a568-d270d66cf34a.png)
![image](https://user-images.githubusercontent.com/14981875/157445383-ebcd9790-0758-4cb1-8aa6-1f243fb41bea.png)

**Comment by xhums1** [comment]
To disable driver signature enforcement do the following:
1.     Press and hold the Shift key on your keyboard and click the Restart button.
2.     Choose Troubleshoot > Advanced options > Startup Settings and click the Restart button.
3.     When your computer restarts you’ll see a list of options. Press F7 on your keyboard to select Disable driver signature enforcement.
4.     Your computer will now restart and the driver will work, **but note that it only works on this restart, after you restart the pc again you have to repeat the process**

**Comment by ibigbug** [comment]
updated to README, thanks!
