### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by mirathewhite** [Watfaq/SoftU2F-Win#17]
I had a couple of compilation errors while trying to build the latest version. 

1. SoftU2FDaemon had a missing RuntimeIdentifier and required C# version 9.0.  The fix was to add the following lines to SoftU2FDaemon.csproj
```
	<RuntimeIdentifier>win10-x64</RuntimeIdentifier>
	<LangVersion>9.0</LangVersion>
```
2. SoftU2FDriver SIGNTASK needed a File Digest Algorithm. This required updating the SoftU2FDriver:
Right click on SoftU2FDriver -> Properties -> Driver Signing -> General
Type SHA256 in the File Digest Algorithm

3. Prior to installing the driver, I needed to execute `Set-ExecutionPolicy RemoteSigned `

**Comment by xhums1** [comment]
error 2 worked for you after you build it? Did you install the driver? I'm not able to properly build it to make it work :(
https://github.com/SoftU2F/SoftU2F-Win/issues/11#issuecomment-1094212360

**Comment by ibigbug** [comment]
the `RuntimeIdentifier` is done here: https://github.com/SoftU2F/SoftU2F-Win/blob/6273591f49720e763d0d712780b41c43e1d9ecc8/azure-pipelines.yml#L45 though you can change it manually

**Comment by ibigbug** [comment]
thanks for reporting. should be addressed by https://github.com/SoftU2F/SoftU2F-Win/pull/23
