### ISSUE TITLE
The operation either timed out or was not allowed

### ISSUE THREAD

**Issue by bouncyweirdo** [Watfaq/SoftU2F-Win#30]
Hi, I installed everything as it says in readme and when I'm trying to test it on demo.yubico.com I get error from subject, also check the picture, any ideas why?

<img width="1066" alt="Screenshot 2022-08-01 at 3 23 11 PM" src="https://user-images.githubusercontent.com/6624317/182149125-1d2e8faa-b297-4593-ad41-d373a730dff1.png">

Thank you

**Comment by MrMaavin** [comment]
Did you follow the instruction that were shown?
What browser do you use?

Something like this should pop up (Edge browser):
![yubico demo english](https://user-images.githubusercontent.com/49553486/182614841-506973f6-12a6-49ff-b8a1-7400def7156a.png)

**Comment by bouncyweirdo** [comment]
Hi, yes I fully followed the instructions:
OS Version: Windows 10 Pro ( no secure boot ) in Test Mode
Chrome Version: 103.0.5060.134
FF version: 103.0.1 (64-bit) with a different error: `The operation failed for an unknown transient reason`
Edge version: Version 103.0.1264.77

Driver is installed, I can see it in Device manager and the Daemon is started, I can see it in tray and also in task manager.

Let me know if you need other info.

**Comment by ibigbug** [comment]
maybe did you turn on the "focus assistant"? when that is on you won't get any notifications.
