### ISSUE TITLE
How to backup

### ISSUE THREAD

**Issue by CordeliaBuckley** [Watfaq/SoftU2F-Win#52]
Hi, If reinstall or use another PC, How to backup. I try to copy "AppData\Roaming\SoftU2FDaemon\db.sqlite" to other PC. But not work, apparently it unfamiliar. BTW The "Exit" didn't work, must end it in task manager.

![](https://i.imgur.com/b9LM4Rj.png)

**Comment by ibigbug** [comment]
I don't think in theory it's possible to back up data.

As in serious case, the keys should be stored in TPM.

the current implementation isn't doing that, but it still has the data saved with DPAPI, so I think only the current person should be able to have access to the data. when back up and restore, it'd become another "person", so it should fail as expected.
