### ISSUE TITLE
USBIP compatibility

### ISSUE THREAD

**Issue by arpruss** [Watfaq/SoftU2F-Win#6]
Have you thought of making this compatible with USBIP, so it could be run with USBIP's signed driver?

**Comment by ibigbug** [comment]
that sounds an interesting topic!

i don't have much experience with USBIP, do you have some learning materials ?

**Comment by ibigbug** [comment]
After having some research, it seems USB/IP only works with USB devices. Unfortunately this driver only creates a HID device, can't see how to make it happen easily at this time.

feel free to reopen if you have any other commetns.
