### ISSUE TITLE
Windows cannot load the device driver for this hardware. The driver may be corrupted or missing. (Code 39)

### ISSUE THREAD

**Issue by directentis1** [Watfaq/SoftU2F-Win#63]
`{Driver Entry Point Not Found}
The %hs device driver could not locate the entry point %hs in driver %hs.`

OS: Windows Server 2019

I followed the exact instructions step by step, from opening PowerShell with Admin rights and running the commands `Set-ExecutionPolicy RemoteSigned`, `bcdedit /set TESTSIGNING OFF`, respectively, but the driver still failed to load and so Cannot open SoftU2FDaemon.

![](https://i.imgur.com/YNaMNEH.png)

**Comment by ibigbug** [comment]
have you tried the latest driver release which is signed and doesn't require debug mode?

**Comment by kattrafd** [comment]
is you solved that? and if u solved how? i get the same problem and dont get why

**Comment by directentis1** [comment]
Yeah, I've solved that by using rust-u2f on my Ubuntu 😂
Well, that's most simple way for me.

**Comment by kattrafd** [comment]
> Yeah, I've solved that by using rust-u2f on my Ubuntu 😂 Well, that's most simple way for me.

is u can help me? i want install rust-u2f too but my linux skills are weird i try many things but still nothing, little guide for me

**Comment by directentis1** [comment]
> is u can help me? i want install rust-u2f too but my linux skills are weird i try many things but still nothing, little guide for me

I think the guide from the author of rust-u2f is the most complete, you just need to run commands like this on Ubuntu and everything will work!
https://github.com/danstiner/rust-u2f#ubuntu
