### ISSUE TITLE
I'm using your software to link electronic keys on YouTube and I'm able to link the first key, but I can't seem to link the second one.

### ISSUE THREAD

**Issue by auauua1234** [Watfaq/SoftU2F-Win#67]
Hi! The question is in the header. I tried installing two different drivers and named them differently, but YouTube recognizes them as one and I'm stuck on this issue.

**Comment by ibigbug** [comment]
do you mean two keys on same computer - you can't do that

**Comment by auauua1234** [comment]
> do you mean two keys on same computer - you can't do that

why?

**Comment by ibigbug** [comment]
Because technically you only have one hardware, which is your computer, and it can't make up two different keys

**Comment by auauua1234** [comment]
> Because technically you only have one hardware, which is your computer, and it can't make up two different keys

maybe if i'am use virtual box is solved problem?

**Comment by ibigbug** [comment]
Yes that should do. But why you want to do that? It doesn't bring extra security I guess ?
