### ISSUE TITLE
Duo compatibility?

### ISSUE THREAD

**Issue by arpruss** [Watfaq/SoftU2F-Win#7]
Is SoftU2F supposed to work with Duo security? I tried it with the Yubikey test site and it worked, but when I tried it with Duo, I got the Soft2U2F popup, I clicked on it, the popup disappeared, and nothing happened: I just had Duo's little window saying that I should press the button on my authentication device, and nothing else happening.

**Comment by ibigbug** [comment]
Should be fixed in https://github.com/SoftU2F/SoftU2F-Win/pull/5

recompiling the daemon project should work or I'll setup new release later

**Comment by ibigbug** [comment]
please try the latest release at https://github.com/SoftU2F/SoftU2F-Win/releases/tag/2021-03-28
